export const UPDATE_MOVIE = 'UPDATE_MOVIE';
export const UPDATE_MOVIES = 'UPDATE_MOVIES';
export const UPDATE_SEARCH_TERM = 'UPDATE_SEARCH_TERM';
export const UPDATE_SEARCH_BY = 'UPDATE_SEARCH_BY';
export const UPDATE_SORT_BY = 'UPDATE_SORT_BY';
